### ISSUE TITLE
Make highlight-sexp available for installation via package.el

### ISSUE THREAD

**Issue by karbak** [daimrod/highlight-sexp#3]
Could this mode be packaged for direct installation using package.el via MELPA or similar?
Thanks.

**Comment by daimrod** [comment]
I've updated the package to make it package.el compliant.

I'll update it on marmalade ASAP but the registration are closed ATM.

**Comment by daimrod** [comment]
It's uploaded on http://marmalade-repo.org/packages/highlight-sexp.

You can install it with `M-x package-install [RET] highlight-sexp [RET]`.
